server:
  port: 8054

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: candidate-service
          uri: lb://candidate-service
          predicates:
            - Path=/candidates/**
          uri: lb://node-service
          predicates:
            - Path=/api/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
